//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhiskyKing.Core.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhiskyKing.Core.Globalization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O grupo de acesso Admin não pode ser modificado..
        /// </summary>
        internal static string AccessGroupAdminCantBeModified {
            get {
                return ResourceManager.GetString("AccessGroupAdminCantBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as mercadorias devem possuir desconto menor ou igual ao subtotal..
        /// </summary>
        internal static string AllMerchandisesMustHaveDiscountAmountEqualsOrLessThanPrice {
            get {
                return ResourceManager.GetString("AllMerchandisesMustHaveDiscountAmountEqualsOrLessThanPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as mercadorias devem possuir desconto igual ou maior que zero..
        /// </summary>
        internal static string AllMerchandisesMustHaveDiscountEqualsOrGreaterThanZero {
            get {
                return ResourceManager.GetString("AllMerchandisesMustHaveDiscountEqualsOrGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as mercadorias devem possuir preço maior que zero..
        /// </summary>
        internal static string AllMerchandisesMustHavePriceGreaterThanZero {
            get {
                return ResourceManager.GetString("AllMerchandisesMustHavePriceGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as mercadorias devem possuir quantidade maior que zero..
        /// </summary>
        internal static string AllMerchandisesMustHaveQuantityGreaterThanZero {
            get {
                return ResourceManager.GetString("AllMerchandisesMustHaveQuantityGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todas as formas de pagamento devem possuir valor maior que zero..
        /// </summary>
        internal static string AllPaymentMethodsMustHaveValueGreaterThanZero {
            get {
                return ResourceManager.GetString("AllPaymentMethodsMustHaveValueGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha atual inválida..
        /// </summary>
        internal static string CurrentPasswordInvalid {
            get {
                return ResourceManager.GetString("CurrentPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O preço da mercadoria deve ser maior que zero..
        /// </summary>
        internal static string InvalidPrice {
            get {
                return ResourceManager.GetString("InvalidPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login já está sendo utilizado..
        /// </summary>
        internal static string LoginAlreadyInUse {
            get {
                return ResourceManager.GetString("LoginAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login deve ter entre 1 e 100 caracteres..
        /// </summary>
        internal static string LoginMustBeBetween1And100Characters {
            get {
                return ResourceManager.GetString("LoginMustBeBetween1And100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Grupos de Acesso.
        /// </summary>
        internal static string ManageAccessGroups {
            get {
                return ResourceManager.GetString("ManageAccessGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Categorias.
        /// </summary>
        internal static string ManageCategories {
            get {
                return ResourceManager.GetString("ManageCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Mercadorias.
        /// </summary>
        internal static string ManageMerchandises {
            get {
                return ResourceManager.GetString("ManageMerchandises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Formas de Pagamento.
        /// </summary>
        internal static string ManagePaymentMethods {
            get {
                return ResourceManager.GetString("ManagePaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Vendas.
        /// </summary>
        internal static string ManageSales {
            get {
                return ResourceManager.GetString("ManageSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Usuários.
        /// </summary>
        internal static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve ter entre 1 e 100 caracteres..
        /// </summary>
        internal static string NameMustBeBetween1And100Characters {
            get {
                return ResourceManager.GetString("NameMustBeBetween1And100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve ter entre 1 e 25 caracteres..
        /// </summary>
        internal static string NameMustBeBetween1And25Characters {
            get {
                return ResourceManager.GetString("NameMustBeBetween1And25Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome deve ter entre 1 e 50 caracteres..
        /// </summary>
        internal static string NameMustBeBetween1And50Characters {
            get {
                return ResourceManager.GetString("NameMustBeBetween1And50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novas senhas não são iguais..
        /// </summary>
        internal static string NewPasswordsInvalid {
            get {
                return ResourceManager.GetString("NewPasswordsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O valor total dos pagamentos deve ser igual ao valor total da venda..
        /// </summary>
        internal static string PaymentsAmountMustBeEqualsToSaleAmount {
            get {
                return ResourceManager.GetString("PaymentsAmountMustBeEqualsToSaleAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro não encontrado..
        /// </summary>
        internal static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há turno em aberto..
        /// </summary>
        internal static string ShiftIsClosed {
            get {
                return ResourceManager.GetString("ShiftIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O usuário Admin não pode ser modificado..
        /// </summary>
        internal static string UserAdminCantBeModified {
            get {
                return ResourceManager.GetString("UserAdminCantBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário ou senha inválidos..
        /// </summary>
        internal static string UserOrPasswordInvalids {
            get {
                return ResourceManager.GetString("UserOrPasswordInvalids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Grupos de Acesso.
        /// </summary>
        internal static string ViewAccessGroups {
            get {
                return ResourceManager.GetString("ViewAccessGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Categorias.
        /// </summary>
        internal static string ViewCategories {
            get {
                return ResourceManager.GetString("ViewCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Mercadorias.
        /// </summary>
        internal static string ViewMerchandises {
            get {
                return ResourceManager.GetString("ViewMerchandises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Formas de Pagamentos.
        /// </summary>
        internal static string ViewPaymentMethods {
            get {
                return ResourceManager.GetString("ViewPaymentMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Vendas.
        /// </summary>
        internal static string ViewSales {
            get {
                return ResourceManager.GetString("ViewSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizar Usuários.
        /// </summary>
        internal static string ViewUsers {
            get {
                return ResourceManager.GetString("ViewUsers", resourceCulture);
            }
        }
    }
}
